### ISSUE TITLE
Bug em horário fora da regra da imagem explicativa

### ISSUE THREAD

**Issue by viniap** [luthierycosta/ConsertandoHorariosSIGAA#1]
Não está convertendo corretamente o seguinte horário: 4T67 4N12. O 4N12 ele converte normalmente, porém o 4T67 não, pelo fato de não haver um T7 no mapa de horários e da exclusão do 7 no regex, o que é compreensível já que a própria imagem explicativa não menciona este caso.

O horário desta disciplina no Matrícula WEB era 18:20 - 20:10, ou seja, aparentemente existem alguns horários fora da regra. No mais parabéns pelo trabalho, ficou excelente!

**Comment by luthierycosta** [comment]
Corrigi o problema adicionando o 7 no mapa, de acordo com o post do instagram da UnB que mostrou a referência de todos os horários. Vlw!
